name: CI Build Steps [called]
on:
  workflow_call:
    secrets:
      TEST_TENANT_ID:
        required: true
      TEST_REGION:
        required: true
      TEST_OAUTH_CLIENT_SECRET:
        required: true
      TEST_OAUTH_CLIENT_ID:
        required: true
      TEST_API_KEY:
        required: true
  push:


jobs:

  check-format:
    runs-on: cx-public-ubuntu-x64
    steps:
      - name: Fetch Code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b

      - name: Check formatting
        run: |
          pip config set global.index-url https://:${{ secrets.ECHO_LIBRARIES_ACCESS_KEY }}@pypi.echohq.com/simple
          pip install . pylint


  execute-pylint:
    runs-on: cx-public-ubuntu-x64
    strategy:
      max-parallel: 2
      matrix:
        pver:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    container: python:${{ matrix.pver }}
    steps:
      - name: Fetch Code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b

      - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d
        with:
          python-version: "3.12"

      - name: Check formatting
        shell: bash
        run: |
          pip config set global.index-url https://:${{ secrets.ECHO_LIBRARIES_ACCESS_KEY }}@pypi.echohq.com/simple
          pip install . black==26.5.1
          black --check .

      - name: Pylint
        shell: bash
        run: |
          pylint --disable=all --enable=E,F --disable=E1121 --score=false cxoneflow_audit

  call-package-build:
    uses: ./.github/workflows/build.yml
    with:
      buildonly: true
