name: CI Build Steps [called]
on:
  workflow_call:
    secrets:
      TEST_TENANT_ID:
        required: true
      TEST_REGION:
        required: true
      TEST_OAUTH_CLIENT_SECRET:
        required: true
      TEST_OAUTH_CLIENT_ID:
        required: true
      TEST_API_KEY:
        required: true
  push:
  schedule:
    - cron: '0 3 * * 1'

permissions:
  contents: read

jobs:

  check-format:
    runs-on: cx-public-ubuntu-x64
    steps:
      - name: Fetch Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Check formatting
        run: |
          pip config set global.index-url https://:${{ secrets.ECHO_LIBRARIES_ACCESS_KEY }}@pypi.echohq.com/simple
          pip install . black==26.5.1
          black --check .


  execute-pylint:
    runs-on: cx-public-ubuntu-x64
    strategy:
      max-parallel: 2
      matrix:
        pver:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
    container: python:${{ matrix.pver }}
    steps:
      - name: Fetch Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Pylint
        shell: bash
        run: |
          pip config set global.index-url https://:${{ secrets.ECHO_LIBRARIES_ACCESS_KEY }}@pypi.echohq.com/simple
          pip install . pylint
          pylint --disable=all --enable=E,F --disable=E1121 --score=false cxoneflow_audit

  call-package-build:
    uses: ./.github/workflows/build-package.yml
    secrets: inherit
    with:
      buildonly: true
