name: Publish a Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version tag to use in the form of x.x.x"
        required: true
        type: string
      prerelease:
        description: "Check if this is to publish a pre-release."
        required: true
        type: boolean

permissions:
  contents: read

jobs:
  tag-repo:
    runs-on: cx-public-ubuntu-x64
    outputs:
      tag: ${{ steps.tag-string.outputs.tag }}
    permissions:
      contents: write
    steps:
      - name: Create tag string
        run: |
          [ ${{ inputs.prerelease }} = false ] && echo "tag=${{ inputs.version }}" >> $GITHUB_OUTPUT || \
            echo "tag=${{ inputs.version }}rc$GITHUB_RUN_NUMBER" >> $GITHUB_OUTPUT
        id: tag-string

      - name: Validate no tag
        run: |
          set +e
          git clone --branch ${{ steps.tag-string.outputs.tag }} --depth=1 $GITHUB_SERVER_URL/$GITHUB_REPOSITORY > /dev/null 2>&1 && exit 1
          set -e

      # - name: Fetch Code
      #   uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      # - name: Set Tag
      #   run: |
      #     git tag '${{ steps.tag-string.outputs.tag }}'
      #     git push origin '${{ steps.tag-string.outputs.tag }}'

  # make-tag-string:
  #   runs-on: cx-public-ubuntu-x64
  #   outputs:
  #     tag: ${{ steps.tag-string.outputs.tag }}
  #   steps:
  #     - name: Create tag string
  #       run: |
  #         [ ${{ inputs.prerelease }} = false ] && echo "tag=${{ inputs.version }}" >> $GITHUB_OUTPUT || \
  #           echo "tag=${{ inputs.version }}rc$GITHUB_RUN_NUMBER" >> $GITHUB_OUTPUT
  #       id: tag-string

  # validate-no-tag:
  #   runs-on: cx-public-ubuntu-x64
  #   needs: [make-tag-string]
  #   steps:
  #     - name: Fetch Code
  #       continue-on-error: true
  #       uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
  #       with:
  #         ref: refs/tags/${{ needs.make-tag-string.outputs.tag }}

  #     - name: Fail if tag ${{ needs.make-tag-string.outputs.tag }} exists
  #       run: |
  #         [[ $(git describe --tags) ==  ${{ needs.make-tag-string.outputs.tag }} ]] && exit 1 || :

  # create-tag:
  #   runs-on: cx-public-ubuntu-x64
  #   needs: [make-tag-string, validate-no-tag]
  #   outputs:
  #     done: ${{ steps.done_check.outputs.status }}
  #   permissions:
  #     contents: write
  #   steps:
  #     - name: Fetch Code
  #       uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        
  #     - name: Set Version
  #       if: ${{ inputs.version != '' }}
  #       run: |
  #         git config --global user.email "${{ github.triggering_actor }}"
  #         git config --global user.name "${{ github.triggering_actor }}"
  #         git tag ${{ needs.make-tag-string.outputs.tag }}
  #         git push origin --tags

  #     - name: Set tag status
  #       id: done_check
  #       run: |
  #         echo "status=true" >> "$GITHUB_OUTPUT"


  check:
    runs-on: cx-public-ubuntu-x64
    needs: [tag-repo]
    steps:
      - name: Echo tag
        run: |
          echo TAG: ${{ needs.tag-repo.outputs.tag }}
          echo VERSION: ${{ inputs.version }}



  # publish-release:
  #   permissions:
  #     contents: write
  #   needs: [make-tag-string, create-tag]
  #   uses: ./.github/workflows/build.yml
  #   with:
  #     version: ${{ needs.make-tag-string.outputs.tag }}
  #     prerelease: ${{ inputs.prerelease }}










  remove-tag-on-failure:
    needs: [make-tag-string, create-tag, publish-release]
    runs-on: cx-public-ubuntu-x64
    permissions:
      contents: write
    if: ${{ failure() && needs.create-tag.outputs.done }}
    steps:
      - name: Fetch Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Remove CodeTag
        run: git push origin ':refs/tags/${{ needs.make-tag-string.outputs.tag }}'
