name: Checkmarx Scan
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - synchronize

env:
  VIRTUALENV_NO_PERIODIC_UPDATE: 1

permissions:
  contents: read

jobs:
  execute-scan:
    runs-on: cx-public-ubuntu-x64
    permissions:
      contents: read
      pull-requests: write
      statuses: write
    steps:
      - name: Fetch Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d
        with:
          python-version: "3.12"

      - name: Setup Python Build Env
        run: |
          pip config set global.index-url https://:${{ secrets.ECHO_LIBRARIES_ACCESS_KEY }}@pypi.echohq.com/simple
          pip install virtualenv

      - name: Scan with CxOne++ Action
        id: cxscan
        uses: checkmarx-ts/cxone-plusplus-github-action@9e69646151d1564d227e7979ce9780b422bdf2f4 # v2
        with:
          cx-tenant: ${{ secrets.CXONE_TENANT }}
          cx-client-id: ${{ secrets.CXONE_CLIENT_ID }}
          cx-client-secret: ${{ secrets.CXONE_CLIENT_SECRET }}
          upload-sarif-file: false
          
